# Generated by Django 4.2.2 on 2024-01-09 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_blogmodel_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactModel',
        ),
    ]
