# Generated by Django 4.2.2 on 2024-01-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='user/'),
        ),
    ]
