# Generated by Django 4.2.2 on 2024-01-09 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_usermodel_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='img',
        ),
    ]
