# Generated by Django 4.2.2 on 2024-01-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_ordermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
