# Generated by Django 4.2.2 on 2024-01-09 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_ordermodel_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='is_active',
        ),
    ]
