# Generated by Django 4.2.2 on 2024-01-11 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_ordermodel_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
